name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  test-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack
    - name: Run tests
      run: cargo llvm-cov --html
