name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Run tests
      run: cargo llvm-cov --html --manifest-path "/home/runner/work/eng-units/eng-units/Cargo.toml"
