name: Test

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always

jobs: 
  test-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --verbose

  test-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --verbose

  test-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update stable
    - name: Run tests
      run: cargo test --verbose
